In [1]:
import pandas as pd
import numpy as np
import datetime as dt
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('data.csv')

In [3]:
df.head().T

0           1           2           3           4
house_pk              84561       84561       84561       84561       84561
agency_id                90          90          90          90          90
date_in          2016-08-27  2016-08-26  2016-08-25  2016-08-24  2016-08-23
price                   532         588         588         588         588
dis_water_real        0.261       0.261       0.261       0.261       0.261
dis_shopping              3           3           3           3           3
no_bedrooms               3           3           3           3           3
max_persons               4           4           4           4           4
house_size              140         140         140         140         140
land_size               726         726         726         726         726
build_year             1953        1953        1953        1953        1953
renovation_year        2014        2014        2014        2014        2014
apartment                 0           0           0           0           0
indoor_pool               0           0           0           0           0
spa                       1           1           1           1           1
internet                  1           1           1           1           1
pets_allowed              0           0           0           0           0
water_view                1           1           1           1           1
fire_stove                1           1           1           1           1
agency_rating             3           3           3           3           3

In [4]:
df.shape

(85195, 20)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85195 entries, 0 to 85194
Data columns (total 20 columns):
house_pk           85195 non-null int64
agency_id          85195 non-null int64
date_in            85195 non-null object
price              85195 non-null int64
dis_water_real     85195 non-null float64
dis_shopping       85195 non-null float64
no_bedrooms        85195 non-null int64
max_persons        85195 non-null int64
house_size         85195 non-null int64
land_size          85195 non-null int64
build_year         85195 non-null int64
renovation_year    85195 non-null int64
apartment          85195 non-null int64
indoor_pool        85195 non-null int64
spa                85195 non-null int64
internet           85195 non-null int64
pets_allowed       85195 non-null int64
water_view         85195 non-null int64
fire_stove         85195 non-null int64
agency_rating      85195 non-null float64
dtypes: float64(3), int64(16), object(1)
memory usage: 13.0+ MB


In [6]:
df.isnull().sum()

house_pk           0
agency_id          0
date_in            0
price              0
dis_water_real     0
dis_shopping       0
no_bedrooms        0
max_persons        0
house_size         0
land_size          0
build_year         0
renovation_year    0
apartment          0
indoor_pool        0
spa                0
internet           0
pets_allowed       0
water_view         0
fire_stove         0
agency_rating      0
dtype: int64

In [7]:
df['date_in'] = pd.to_datetime(df['date_in'])

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85195 entries, 0 to 85194
Data columns (total 20 columns):
house_pk           85195 non-null int64
agency_id          85195 non-null int64
date_in            85195 non-null datetime64[ns]
price              85195 non-null int64
dis_water_real     85195 non-null float64
dis_shopping       85195 non-null float64
no_bedrooms        85195 non-null int64
max_persons        85195 non-null int64
house_size         85195 non-null int64
land_size          85195 non-null int64
build_year         85195 non-null int64
renovation_year    85195 non-null int64
apartment          85195 non-null int64
indoor_pool        85195 non-null int64
spa                85195 non-null int64
internet           85195 non-null int64
pets_allowed       85195 non-null int64
water_view         85195 non-null int64
fire_stove         85195 non-null int64
agency_rating      85195 non-null float64
dtypes: datetime64[ns](1), float64(3), int64(16)
memory usage: 13.0 MB


In [9]:
df['date_in'] = df['date_in'].map(dt.datetime.toordinal)

In [10]:
df.head().T

0           1           2           3           4
house_pk          84561.000   84561.000   84561.000   84561.000   84561.000
agency_id            90.000      90.000      90.000      90.000      90.000
date_in          736203.000  736202.000  736201.000  736200.000  736199.000
price               532.000     588.000     588.000     588.000     588.000
dis_water_real        0.261       0.261       0.261       0.261       0.261
dis_shopping          3.000       3.000       3.000       3.000       3.000
no_bedrooms           3.000       3.000       3.000       3.000       3.000
max_persons           4.000       4.000       4.000       4.000       4.000
house_size          140.000     140.000     140.000     140.000     140.000
land_size           726.000     726.000     726.000     726.000     726.000
build_year         1953.000    1953.000    1953.000    1953.000    1953.000
renovation_year    2014.000    2014.000    2014.000    2014.000    2014.000
apartment             0.000       0.000       0.000       0.000       0.000
indoor_pool           0.000       0.000       0.000       0.000       0.000
spa                   1.000       1.000       1.000       1.000       1.000
internet              1.000       1.000       1.000       1.000       1.000
pets_allowed          0.000       0.000       0.000       0.000       0.000
water_view            1.000       1.000       1.000       1.000       1.000
fire_stove            1.000       1.000       1.000       1.000       1.000
agency_rating         3.000       3.000       3.000       3.000       3.000

In [11]:
len(df.agency_rating.unique())

4

In [12]:
from sklearn.preprocessing import MinMaxScaler

In [13]:
scaler = MinMaxScaler(feature_range=(0,1))

In [14]:
y_data = df['price']

In [15]:
type(y_data)

pandas.core.series.Series

In [16]:
x_data = df.drop('price',axis=1)

In [17]:
type(x_data)

pandas.core.frame.DataFrame

In [18]:
x_data.shape

(85195, 19)

In [19]:
y_data.shape

(85195,)

In [20]:
y_data = y_data.values

In [21]:
print(y_data.shape, type(y_data))

(85195,) <class 'numpy.ndarray'>


In [22]:
y_data = y_data.reshape(-1,1)

In [23]:
y_data = y_data.astype(np.float32)
y_data

array([[532.],
       [588.],
       [588.],
       ...,
       [308.],
       [312.],
       [308.]], dtype=float32)

In [24]:
x_data = x_data.drop('house_pk',axis =1 )
x_data.head()

agency_id  date_in  dis_water_real  dis_shopping  no_bedrooms  max_persons  \
0         90   736203           0.261           3.0            3            4   
1         90   736202           0.261           3.0            3            4   
2         90   736201           0.261           3.0            3            4   
3         90   736200           0.261           3.0            3            4   
4         90   736199           0.261           3.0            3            4   

   house_size  land_size  build_year  renovation_year  apartment  indoor_pool  \
0         140        726        1953             2014          0            0   
1         140        726        1953             2014          0            0   
2         140        726        1953             2014          0            0   
3         140        726        1953             2014          0            0   
4         140        726        1953             2014          0            0   

   spa  internet  pets_allowed  water_view  fire_stove  agency_rating  
0    1         1             0           1           1            3.0  
1    1         1             0           1           1            3.0  
2    1         1             0           1           1            3.0  
3    1         1             0           1           1            3.0  
4    1         1             0           1           1            3.0

In [25]:
x_data = x_data.values
x_data = x_data.astype(np.float32)

In [26]:
type(x_data)

numpy.ndarray

In [27]:
x_data_scaled = scaler.fit_transform(x_data)
x_data_scaled

array([[0.        , 0.1887207 , 0.00572884, ..., 1.        , 1.        ,
        0.3333333 ],
       [0.        , 0.18786621, 0.00572884, ..., 1.        , 1.        ,
        0.3333333 ],
       [0.        , 0.18701172, 0.00572884, ..., 1.        , 1.        ,
        0.3333333 ],
       ...,
       [0.        , 0.9848633 , 0.01512325, ..., 0.        , 1.        ,
        0.6666667 ],
       [0.        , 0.9940796 , 0.01512325, ..., 0.        , 1.        ,
        0.6666667 ],
       [0.        , 0.99072266, 0.01512325, ..., 0.        , 1.        ,
        0.6666667 ]], dtype=float32)

In [28]:
y_data_scaled = scaler.fit_transform(y_data)

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
batch_size = 100

In [31]:
X_train, X_test, y_train, y_test = train_test_split(x_data_scaled, y_data_scaled, test_size=0.1, random_state=42)

In [32]:
import torch
import torch.nn as nn
from torch.autograd import Variable

In [33]:
X_train_torch = torch.from_numpy(X_train)
y_train_torch = torch.from_numpy(y_train)
X_test_torch = torch.from_numpy(X_test)
y_test_torch = torch.from_numpy(y_test)

In [34]:
class Test(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super(Test, self).__init__()
        
        self.linear1 = nn.Linear(input_dim, hidden_dim)
        self.linear2 = nn.Linear(hidden_dim, hidden_dim)
        self.linear3 = nn.Linear(hidden_dim, output_dim)
        
        self.relu = nn.ReLU()
        
    def forward(self, x):
        
        out = self.relu(self.linear1(x))
        out = self.relu(self.linear2(out))
        out = self.linear3(out)
        
        return out

In [35]:
input_dim = 18
output_dim = 1
hidden_dim = 50

model = Test(input_dim, hidden_dim, output_dim)
print(model)

Test(
  (linear1): Linear(in_features=18, out_features=50, bias=True)
  (linear2): Linear(in_features=50, out_features=50, bias=True)
  (linear3): Linear(in_features=50, out_features=1, bias=True)
  (relu): ReLU()
)


In [36]:
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr= 0.01)

In [37]:
epochs = 50

for epoch in range(epochs):
    
    
        
    X_train_torch = Variable(X_train_torch)

    y_train_torch = Variable(y_train_torch)

    optimizer.zero_grad()

    output = model(X_train_torch)

    loss = criterion(output, y_train_torch)

    print('loss: {:.4f}'.format(loss.item()))

    loss.backward()

    optimizer.step()

loss: 0.0828
loss: 0.0774
loss: 0.0723
loss: 0.0677
loss: 0.0634
loss: 0.0594
loss: 0.0557
loss: 0.0524
loss: 0.0492
loss: 0.0463
loss: 0.0437
loss: 0.0412
loss: 0.0390
loss: 0.0369
loss: 0.0349
loss: 0.0332
loss: 0.0315
loss: 0.0300
loss: 0.0286
loss: 0.0273
loss: 0.0261
loss: 0.0250
loss: 0.0240
loss: 0.0231
loss: 0.0223
loss: 0.0215
loss: 0.0207
loss: 0.0201
loss: 0.0195
loss: 0.0189
loss: 0.0184
loss: 0.0179
loss: 0.0175
loss: 0.0171
loss: 0.0167
loss: 0.0163
loss: 0.0160
loss: 0.0157
loss: 0.0155
loss: 0.0152
loss: 0.0150
loss: 0.0148
loss: 0.0146
loss: 0.0144
loss: 0.0143
loss: 0.0141
loss: 0.0140
loss: 0.0138
loss: 0.0137
loss: 0.0136


In [38]:
predicted = model.forward(Variable(X_test_torch)).data.numpy()

In [39]:
predicted

array([[0.14103636],
       [0.18918504],
       [0.16326526],
       ...,
       [0.190967  ],
       [0.13252166],
       [0.1917032 ]], dtype=float32)

In [40]:
from sklearn.metrics import mean_squared_error

In [41]:
rmse = np.sqrt(mean_squared_error(predicted, y_test))

print(rmse)

0.11688499


In [42]:
predicted_original = scaler.inverse_transform(predicted)
y_test_original = scaler.inverse_transform(y_test)

In [43]:
predicted_original

array([[403.1567 ],
       [531.2322 ],
       [462.28558],
       ...,
       [535.97217],
       [380.5076 ],
       [537.9305 ]], dtype=float32)

In [44]:
y_test_original

array([[287.     ],
       [364.     ],
       [357.     ],
       ...,
       [791.00006],
       [322.     ],
       [875.     ]], dtype=float32)